/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Konest.Project.EmployeeDataBase;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Ranjith
 */
public class UpdateEmployee extends javax.swing.JFrame {

    /**
     * Creates new form UpdateEmployee
     */
      Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        String dpath = "com.mysql.cj.jdbc.Driver";
        String url  = "jdbc:mysql://localhost:3306/employee12";
        String user = "root";
        String password = "ranju";
    public UpdateEmployee() {
        initComponents();
        acti();
    }
    
    public void acti() {
        idText.addActionListener(new ActionListener(){
          
            public void actionPerformed(ActionEvent e) {
                updateEmp();
            }
        });
         }
    
    public void updateEmp() {
        String sql = "select * from employee13 where id = ?";
        Scanner scan = new Scanner(System.in);
        
        
        try {
            Class.forName(dpath);
            con = DriverManager.getConnection(url,user,password);
            ps = con.prepareStatement(sql);
            int id = Integer.parseInt(idText.getText());
            ps.setInt(1, id);
            
            rs = ps.executeQuery();
            
            if(rs.next()) {
               nameText.setText(rs.getString(2));
               nameText.setEditable(false);
               emailText.setText(rs.getString(3));
               emailText.setEditable(false);
               salarytext.setText(String.valueOf(rs.getInt(4)));
               salarytext.setEditable(false);
               phoneNo.setText(String.valueOf(rs.getLong(5)));
               phoneNo.setEditable(false);
               addresstext.setText(rs.getString(6));
               addresstext.setEditable(false);
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Wrong Id Entered, Please Enter Valid Id between 1 to 10","Warning",JOptionPane.WARNING_MESSAGE);
               
            }
            
        }
        catch(Exception e) {
        e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nameCheck = new javax.swing.JCheckBox();
        emailCheck = new javax.swing.JCheckBox();
        salaryCheck = new javax.swing.JCheckBox();
        phoneCheck = new javax.swing.JCheckBox();
        AddressCheck = new javax.swing.JCheckBox();
        updat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        salarytext = new javax.swing.JTextField();
        phoneNo = new javax.swing.JTextField();
        addresstext = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id");

        nameCheck.setText("Name");
        nameCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCheckActionPerformed(evt);
            }
        });

        emailCheck.setText("email");
        emailCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailCheckActionPerformed(evt);
            }
        });

        salaryCheck.setText("Salary");
        salaryCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryCheckActionPerformed(evt);
            }
        });

        phoneCheck.setText("PhoneNo");
        phoneCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneCheckActionPerformed(evt);
            }
        });

        AddressCheck.setText("Address");
        AddressCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressCheckActionPerformed(evt);
            }
        });

        updat.setText("Update");
        updat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Email");

        jLabel4.setText("Salary");

        jLabel5.setText("PhoneNo");

        jLabel6.setText("Address");

        jButton1.setText("Updated Database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(salarytext, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(phoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(nameCheck)
                        .addGap(26, 26, 26)
                        .addComponent(emailCheck)
                        .addGap(12, 12, 12)
                        .addComponent(salaryCheck)
                        .addGap(12, 12, 12)
                        .addComponent(phoneCheck)
                        .addGap(12, 12, 12)
                        .addComponent(AddressCheck))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(131, 131, 131)
                            .addComponent(updat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameCheck)
                    .addComponent(emailCheck)
                    .addComponent(salaryCheck)
                    .addComponent(phoneCheck)
                    .addComponent(AddressCheck))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4))
                    .addComponent(salarytext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5))
                    .addComponent(phoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(addresstext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(updat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String originalEmail = "";
    private void emailCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCheckActionPerformed
        // TODO add your handling code here:
        if(emailCheck.isSelected()) {
        originalEmail = emailText.getText();
        emailText.setEditable(true);
        }
        else {
            emailText.setText(originalEmail);
            emailText.setEditable(false);
        }
    }//GEN-LAST:event_emailCheckActionPerformed

    private void AddressCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressCheckActionPerformed
        // TODO add your handling code here:
        if(AddressCheck.isSelected()) {
        addresstext.setEditable(true);
        }
        else {
            addresstext.setEditable(false);
        }
    }//GEN-LAST:event_AddressCheckActionPerformed

    private void nameCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCheckActionPerformed
        // TODO add your handling code here:
        if(nameCheck.isSelected()) {
        nameText.setEditable(true);
        }
        else {
            nameText.setEditable(false);
        }
    }//GEN-LAST:event_nameCheckActionPerformed

    private void salaryCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryCheckActionPerformed
        // TODO add your handling code here:
        if(salaryCheck.isSelected()) {
        salarytext.setEditable(true);
        }
        else {
            salarytext.setEditable(false);
        }
    }//GEN-LAST:event_salaryCheckActionPerformed

    private void phoneCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneCheckActionPerformed
        // TODO add your handling code here:
        if(phoneCheck.isSelected()) {
        phoneNo.setEditable(true);
        }
        else {
            phoneNo.setEditable(false);
        }
    }//GEN-LAST:event_phoneCheckActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EmployeeDetails ed = new EmployeeDetails();
        ed.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EmployeeHomePage eh = new EmployeeHomePage();
        eh.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatActionPerformed
        // TODO add your handling code here:
        updatedata();
    }//GEN-LAST:event_updatActionPerformed

    
    public void updatedata(){
        String sql = "UPDATE employee13 SET name = ?, email = ?, salary = ?, phoneNo = ?, address = ? WHERE id = ?";
        Scanner scan = new Scanner(System.in);
        try {
        Class.forName(dpath);
        con = DriverManager.getConnection(url,user,password);
        ps = con.prepareStatement(sql);
        String name = nameText.getText();
        String email = emailText.getText();
        int salary = Integer.parseInt(salarytext.getText());
        Long phoneno = Long.parseLong(phoneNo.getText());
        String address = addresstext.getText();
        int id = Integer.parseInt(idText.getText());
        ps.setString(1,name);
        ps.setString(2, email);
        ps.setInt(3, salary);
        ps.setLong(4, phoneno);
        ps.setString(5, address);
        ps.setInt(6, id);
        int nora = ps.executeUpdate();
        if(nora > 0) {
            JOptionPane.showMessageDialog(rootPane, "Employee got Updated Successfully");
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Invalid Credentials", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        }
        catch(Exception e) {
            e.printStackTrace();
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AddressCheck;
    private javax.swing.JTextField addresstext;
    private javax.swing.JCheckBox emailCheck;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox nameCheck;
    private javax.swing.JTextField nameText;
    private javax.swing.JCheckBox phoneCheck;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JCheckBox salaryCheck;
    private javax.swing.JTextField salarytext;
    private javax.swing.JButton updat;
    // End of variables declaration//GEN-END:variables
}
